version: "3.9"
services:
  app:
    container_name: docker-urlshortner
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - sqlite-container

  sqlite-container:
    container_name: sqlite_db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sqlite_data:/database

    command: ["tail", "-f", "/dev/null"]